from utils import find_crams, get_basenames

# =============================================================================
# Too lazy to make a config file
INPUT_DIR = "/path/to/input/directory"
OUTPUT_DIR = "/path/to/output/directory"
REFERENCE_GENOME = "/path/to/reference/genome.fa"
SINGULARITY_CONTAINER = "/path/to/singularity/container.sif"
# =============================================================================

cram_files = find_crams(INPUT_DIR)
sample_names = get_basenames(cram_files)

# Main rule
rule all:
    input:
        raise NotImplementedError("Output files not yet defined")



rule ExcordLR:
    input:
        cram = f"{INPUT_DIR}/{{sample}}.cram"
        reference_genome = REFERENCE_GENOME,
    output:
        bed=temp(f"{OUTPUT_DIR}/excord_beds/{{sample}}.excord.bed")
    shell:
        "bash scripts/run-excord-lr.sh -i {input.cram} -r {input.reference_genome} -o {output.bed} -c "

rule BgzipBed:
    input:
        bed = rules.ExcordLR.output.bed
    output:
        bed = rules.ExcordLR.output.bed + ".gz"
    shell:
        "bgzip -c {input.bed} > {output.bed}"

rule GiggleIndex:
    input:
        expand(rules.BgzipBed.output.bed, sample=sample_names)
    output:
        directory(f"{OUTPUT_DIR}/giggle_index")

rule StixIndex:
    input:
        giggle_index = rules.GiggleIndex.output,
        bed_dir = rules.BgzipBed.output.bed
    output:
        ped = f"{OUTPUT_DIR}/COLO829-SMAHT.ped",
        db = f"{OUTPUT_DIR}/COLO829-SMAHT.ped.db"
    shell:
        "bash scripts/make_stix_index.sh -g {input.giggle_index} -b {input.bed_dir} -n COLO829-SMAHT -o {output.dir}"
